version: '3.9'

services:
  like:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: like
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/likedb
      - SPRING_DATASOURCE_USERNAME=like
      - SPRING_DATASOURCE_PASSWORD=like123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
    ports:
      - "8080:8080"

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=like
      - POSTGRES_PASSWORD=like123
      - POSTGRES_DB=likedb
